# Site settings
baseurl = "http://www.medievalmemes.co/"
languageCode = "en-us"
title = "Medieval Memes"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Medieval Memes"
    subtitle = "Medievalmemes.co is the collector's dream come true. Focused on secondary markets and ultimate scarcity."
    description = "Medievalmemes.co is the collector's dream come true. Focused on secondary markets and ultimate scarcity."
    keywords = "nft,memes,meme,medieval memes,wax,atomic market,collectables,collection"

    # Body background color
    bodybgcolor = "#AF601A"

    # Preview container button text
    buttontext = "Get your free NFT on Atomic Market"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
