# Site settings
baseurl = "http://crypto.medievalmemes.co/"
languageCode = "en-us"
title = "Medieval Memes - Crypto Edition"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Medieval Memes - Crypto Edition"
    subtitle = "A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."

    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "nft,memes,meme,medieval memes,wax,atomic market,collectables,collection"

    # Body background color
    bodybgcolor = "#935116"

    # Preview container button text
    buttontext = "Buy on Atomic Market"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
